@startuml
|people|
start
:input;
|lengthValidation|
while(length ok?) is (no)
:show "length tips";
|people|
:retype1;

endwhile (yes)
|userChecker|
while(unUsed?) is (yes)
:show "used";
|people|
:retype2;
endwhile (no)
|userChecker|
:show "unUsed";
stop
@enduml